### ISSUE TITLE
HeadedDemo is not accessible from a browser

### ISSUE THREAD

**Issue by aquisio** [tomkuijsten/restup#64] opened 2016-06-10 08:31 UTC
Apologies in advance: I realize that this issue has been discussed in a previous thread, but none of the  recommendations in that thread have helped me.

When running HeadedDemo, either debugging from within Visual Studio 2015 or directly from Windows 10, it works fine. However, I am unable to access it from a browser, either on the local machine or remotely.

I have tried disabling the Windows firewall but it makes no difference.

I have also experimented with Fiddler and found that HeadedDemo stops working when Fiddler is running. In this configuration the HeadedDemo client receives a message back from Fiddler, indicating that its onward request to the server timed out.

Any suggestions please?

**Comment by dm-CaT** [comment] 2016-06-10 08:36
Did you try to run demo using web server's source codes instead of NuGet packages?

**Comment by Jark** [comment] 2016-06-10 08:39
Hello Aquisio, 

Locally you can't access anything hosted by StreamSocketListener (which is used by restup internally), this is by design by Microsoft. In the HeadedDemo we get around by this because apps are allowed to connect to StreamSocketListeners hosted in the same process. See http://stackoverflow.com/questions/32665847/cannot-connect-to-streamsocketlistener.

Remotely you should be able to access the HeadedDemo, would you mind checking what you have got in your app manifest of the program you're trying to run?

![image](https://cloud.githubusercontent.com/assets/754147/15958730/2fc182cc-2eef-11e6-8874-181d384a76b2.png)

Cheers,

Jark

**Comment by aquisio** [comment] 2016-06-10 09:16
Hello Jark,

Many thanks for your very quick reply.

Yes, I'm sorry - you're right. The manifest is correctly configured (I cloned your GitHub repo) and it does indeed work remotely. I'm not sure what I did wrong in my earlier remote tests, but it is definitely working now.

Is there any workaround that will enable me to test my app locally from the machine that it is being developed on?

Thanks again for your support. Restup looks like an awesome project that is very much needed.

**Comment by tomkuijsten** [comment] 2016-06-10 09:54
Should we add something to the Wiki? If you run into this issue, more people will.

**Comment by Jark** [comment] 2016-06-10 09:58
Hello Aquisio,

Unfortunately I don't know of any way... I have tried the loopback exemption, but that apparently just doesn't work... (https://msdn.microsoft.com/en-us/library/windows/apps/Hh780593.aspx).

This is the reason why I expanded the HeadedDemo ui to include a way to test the local server, maybe you can do something similar? E.g. conditional debug statements that include the test ui?

@tomkuijsten I already added this info here before: https://github.com/tomkuijsten/restup/wiki/Limitations, but I think it can do with some expanding, and maybe a rename to FAQ that features a bit more prominently on the main page.

**Comment by dm-CaT** [comment] 2016-06-10 10:00
I think it should be included somewhere on top of wiki. ;)
I faced the same problem and spent about an hour to find the solution.

**Comment by Jark** [comment] 2016-06-10 10:02
That seals it, seems the wiki needs a little bit of work done to it, I'll take care of it today.

**Comment by tomkuijsten** [comment] 2016-06-10 10:05
Good, just created a custom menu. You can change it if you like.

**Comment by aquisio** [comment] 2016-06-10 10:45
Thanks to everyone for your guidance. Now that I know about this limitation, it's easy enough to work around using 2 machines.

**Comment by Jark** [comment] 2016-06-12 20:11
I've renamed the Limitations page to FAQ and have added to it: https://github.com/tomkuijsten/restup/wiki/FAQ, I've also added a CONTRIBUTING.MD so that when a new issue is raised they get referred to the FAQ first.

With this, I'm closing this issue.

**Closed by Jark** 2016-06-12 20:11 UTC
